#!/bin/bash

## inverse xforms standard Pauli VTA ROI into subject space using ANTs output
## inverse transform uses ANTs and ITK
## inverse transform requires a brain image (subject t1)

subT1=`jq -r '.t1' config.json`
VTA='masks/MNI152_prob_atlas_vta_pauli.nii.gz'
affine='ants_xform0GenericAffine.mat'
invWarp='ants_xform1InverseWarp.nii.gz'

echo "Warping Pauli VTA ROI into subject space..."

antsApplyTransforms -d 3 \
	-i $VTA \
	-r $subT1 \
	-t [$affine, 1] \
	-t $invWarp \
	-o 'ants_xform_vta.nii.gz'

echo "Pauli VTA ROI xformed into subject space"
