#!/bin/bash

## this script threshold the xformed Pauli VTA roi created by inverseXformVTA
## threshold values are specified in the test_config.json file
## to forgo thresholding, enter a value of 0 into the test_config.json file
## thresholding requires fslmaths

subVTA='ROIs/ants_xform_vta_mask.nii.gz'
thresh=`jq -r '.maskThreshold' config.json`

echo "Thresholding VTA ROI..."

fslmaths $subVTA -thr $thresh "ROIs/ants_xform_vta_thr"$thresh"_mask.nii.gz"

echo "Thresholding completed"
